import { QuizQuestion } from '../types/index.js';

export interface CategorizedQuestion extends QuizQuestion {
  category: 'python' | 'data_structures' | 'algorithms' | 'sql' | 'machine_learning' | 'system_design' | 'cybersecurity';
  concept: string;
}

export const QUESTION_BANK: CategorizedQuestion[] = [
  // ==========================================
  // 1. PYTHON: BEGINNER
  // ==========================================
  {
    id: 'py_beg_1',
    category: 'python',
    difficulty: 'Beginner',
    topic: 'Python Basics',
    concept: 'Mutability & Data Types',
    type: 'multiple_choice',
    question: 'Which of the following built-in Python data types is immutable?',
    options: ['List', 'Dictionary', 'Tuple', 'Set'],
    correctAnswer: 'Tuple',
    explanation: 'Tuples in Python cannot be modified after creation, making them immutable and hashable if their elements are also hashable.',
  },
  {
    id: 'py_beg_2',
    category: 'python',
    difficulty: 'Beginner',
    topic: 'Python Basics',
    concept: 'String Slicing',
    type: 'multiple_choice',
    question: 'What is the result of `"Python"[1:4]` in Python?',
    options: ['"Pyt"', '"yth"', '"ytho"', '"y"'],
    correctAnswer: '"yth"',
    explanation: 'Slicing `[1:4]` starts at index 1 ("y") and ends before index 4 ("o"), returning "yth".',
  },
  {
    id: 'py_beg_3',
    category: 'python',
    difficulty: 'Beginner',
    topic: 'Python Basics',
    concept: 'Dictionary Keys',
    type: 'true_false',
    question: 'A Python list can be used as a key in a standard dictionary.',
    options: ['True', 'False'],
    correctAnswer: 'False',
    explanation: 'Dictionary keys must be hashable. Lists are mutable and unhashable, so attempting to use a list as a dictionary key raises a TypeError.',
  },
  {
    id: 'py_beg_4',
    category: 'python',
    difficulty: 'Beginner',
    topic: 'Python Basics',
    concept: 'List Comprehensions',
    type: 'multiple_choice',
    question: 'What is the output of `[x * 2 for x in range(4) if x % 2 == 0]`?',
    options: ['[0, 4]', '[0, 2, 4]', '[2, 4]', '[0, 2, 4, 6]'],
    correctAnswer: '[0, 4]',
    explanation: '`range(4)` produces 0, 1, 2, 3. The even numbers are 0 and 2. Multiplying them by 2 gives [0, 4].',
  },
  {
    id: 'py_beg_5',
    category: 'python',
    difficulty: 'Beginner',
    topic: 'Python Basics',
    concept: 'Boolean Truthiness',
    type: 'short_answer',
    question: 'In Python, what is the boolean evaluation of an empty list `bool([])`? (Answer True or False)',
    correctAnswer: 'False',
    explanation: 'In Python, empty sequences and collections (such as [], {}, "", set()) evaluate to False in a boolean context.',
  },

  // ==========================================
  // 1. PYTHON: INTERMEDIATE
  // ==========================================
  {
    id: 'py_int_1',
    category: 'python',
    difficulty: 'Intermediate',
    topic: 'Python Core & Concurrency',
    concept: 'Default Mutable Arguments',
    type: 'multiple_choice',
    question: 'What happens when a Python function has a default parameter `def append_to(item, target=[])`?',
    options: [
      'A new list is created on every function call',
      'The same list is reused across subsequent calls, causing shared state',
      'Python raises a SyntaxError at compile time',
      'The list is automatically cleared after each return',
    ],
    correctAnswer: 'The same list is reused across subsequent calls, causing shared state',
    explanation: 'Default parameter values are evaluated once when the function definition is executed, so mutable defaults persist mutations across calls.',
  },
  {
    id: 'py_int_2',
    category: 'python',
    difficulty: 'Intermediate',
    topic: 'Python Core & Concurrency',
    concept: 'Generators & Yield',
    type: 'multiple_choice',
    question: 'What is the primary memory advantage of using a generator function with `yield` instead of returning a list?',
    options: [
      'Generators execute multithreaded bytecode in parallel',
      'Generators stream elements on-demand with O(1) auxiliary memory rather than allocating all items in RAM',
      'Generators automatically compile Python bytecode into C extensions',
      'Generators prevent recursion limit errors',
    ],
    correctAnswer: 'Generators stream elements on-demand with O(1) auxiliary memory rather than allocating all items in RAM',
    explanation: 'Generators compute values lazily one-by-one via the iterator protocol, maintaining a fixed memory footprint regardless of stream length.',
  },
  {
    id: 'py_int_3',
    category: 'python',
    difficulty: 'Intermediate',
    topic: 'Python Core & Concurrency',
    concept: 'Context Managers',
    type: 'multiple_choice',
    question: 'Which special dunder methods must a class implement to support the `with` context manager statement?',
    options: [
      '__start__ and __stop__',
      '__enter__ and __exit__',
      '__open__ and __close__',
      '__begin__ and __commit__',
    ],
    correctAnswer: '__enter__ and __exit__',
    explanation: 'The context manager protocol requires `__enter__()` for setup (executed when entering the block) and `__exit__()` for teardown/cleanup.',
  },
  {
    id: 'py_int_4',
    category: 'python',
    difficulty: 'Intermediate',
    topic: 'Python Core & Concurrency',
    concept: 'Decorators & Closures',
    type: 'true_false',
    question: 'A Python decorator is a higher-order function that takes a function as an argument and returns a wrapped function.',
    options: ['True', 'False'],
    correctAnswer: 'True',
    explanation: 'True. Decorators wrap callable objects to extend or modify their behavior dynamically using closures.',
  },
  {
    id: 'py_int_5',
    category: 'python',
    difficulty: 'Intermediate',
    topic: 'Python Core & Concurrency',
    concept: 'Scope Resolution (LEGB)',
    type: 'multiple_choice',
    question: 'In Python, what is the exact order of namespaces searched during variable lookup (LEGB rule)?',
    options: [
      'Local -> Enclosing -> Global -> Built-in',
      'Local -> Global -> Enclosing -> Built-in',
      'Global -> Local -> Enclosing -> Built-in',
      'Built-in -> Global -> Enclosing -> Local',
    ],
    correctAnswer: 'Local -> Enclosing -> Global -> Built-in',
    explanation: 'Python resolves identifiers starting from Local scope, outward to Enclosing function closures, then Global module namespace, and finally Built-in.',
  },

  // ==========================================
  // 1. PYTHON: ADVANCED
  // ==========================================
  {
    id: 'py_adv_1',
    category: 'python',
    difficulty: 'Advanced',
    topic: 'Python Core & Concurrency',
    concept: 'CPython GIL & Parallelism',
    type: 'multiple_choice',
    question: 'Why does CPython Global Interpreter Lock (GIL) prevent CPU-bound speedups with `threading.Thread` on multi-core processors?',
    options: [
      'The operating system kernel scheduler restricts Python to CPU Core 0',
      'The GIL mutex mandates that only one native OS thread can execute CPython bytecode at any given instant',
      'Python threads use cooperative green threads rather than native OS threads',
      'CPython bytecode lacks arithmetic vectorization instructions',
    ],
    correctAnswer: 'The GIL mutex mandates that only one native OS thread can execute CPython bytecode at any given instant',
    explanation: 'The GIL is a mutex safeguarding CPython memory management and reference counting. CPU-bound parallelism requires `multiprocessing` or native C extensions releasing the GIL.',
  },
  {
    id: 'py_adv_2',
    category: 'python',
    difficulty: 'Advanced',
    topic: 'Python Core & Concurrency',
    concept: 'Metaclasses & Class Construction',
    type: 'multiple_choice',
    question: 'When creating a custom metaclass in Python, which method is responsible for constructing and returning the new class object itself?',
    options: ['__init__', '__new__', '__call__', '__prepare__'],
    correctAnswer: '__new__',
    explanation: 'Metaclass `__new__(mcs, name, bases, attrs)` allocates and constructs the actual class object in memory before `__init__` initializes it.',
  },
  {
    id: 'py_adv_3',
    category: 'python',
    difficulty: 'Advanced',
    topic: 'Python Core & Concurrency',
    concept: 'Memory Optimization with __slots__',
    type: 'multiple_choice',
    question: 'What is the primary architectural effect of defining `__slots__ = ("x", "y")` on a Python class?',
    options: [
      'It prevents subclassing of the class',
      'It suppresses the dynamic per-instance `__dict__`, storing attributes in a fixed-size compact C array to drastically reduce RAM overhead',
      'It forces all attributes to become private and immutable',
      'It converts instance methods into static C-level functions',
    ],
    correctAnswer: 'It suppresses the dynamic per-instance `__dict__`, storing attributes in a fixed-size compact C array to drastically reduce RAM overhead',
    explanation: 'By eliminating the standard dictionary `__dict__` for each instance, `__slots__` saves memory and speeds up attribute access in large-scale datasets.',
  },
  {
    id: 'py_adv_4',
    category: 'python',
    difficulty: 'Advanced',
    topic: 'Python Core & Concurrency',
    concept: 'Garbage Collection & Cyclic References',
    type: 'true_false',
    question: 'CPython generational garbage collector is required because reference counting alone cannot collect isolated objects with circular cross-references.',
    options: ['True', 'False'],
    correctAnswer: 'True',
    explanation: 'True. Reference counting deallocates memory immediately when count reaches 0, but circular references (A -> B -> A) require generational cyclic GC to detect and free.',
  },
  {
    id: 'py_adv_5',
    category: 'python',
    difficulty: 'Advanced',
    topic: 'Python Core & Concurrency',
    concept: 'Descriptor Protocol',
    type: 'multiple_choice',
    question: 'What constitutes a "Data Descriptor" in Python?',
    options: [
      'An object defining only `__get__`',
      'An object defining both `__get__` and at least `__set__` or `__delete__`',
      'Any function wrapped with `@classmethod`',
      'A class inheriting from `dataclass`',
    ],
    correctAnswer: 'An object defining both `__get__` and at least `__set__` or `__delete__`',
    explanation: 'Data descriptors define `__set__` or `__delete__` in addition to `__get__`. In Python attribute lookup precedence, Data Descriptors take priority over instance `__dict__` entries.',
  },

  // ==========================================
  // 2. DATA STRUCTURES: BEGINNER
  // ==========================================
  {
    id: 'dsa_beg_1',
    category: 'data_structures',
    difficulty: 'Beginner',
    topic: 'Data Structures',
    concept: 'Arrays vs Linked Lists',
    type: 'multiple_choice',
    question: 'What is the time complexity of accessing an arbitrary element by index in a standard array?',
    options: ['O(1)', 'O(N)', 'O(log N)', 'O(N^2)'],
    correctAnswer: 'O(1)',
    explanation: 'Arrays allocate contiguous memory blocks, allowing direct pointer arithmetic calculation `base_address + index * element_size` in O(1) constant time.',
  },
  {
    id: 'dsa_beg_2',
    category: 'data_structures',
    difficulty: 'Beginner',
    topic: 'Data Structures',
    concept: 'Stack Invariants',
    type: 'multiple_choice',
    question: 'Which ordering principle governs a Stack data structure?',
    options: ['FIFO (First-In, First-Out)', 'LIFO (Last-In, First-Out)', 'Random Access', 'Priority-Based'],
    correctAnswer: 'LIFO (Last-In, First-Out)',
    explanation: 'A Stack operates strictly as Last-In, First-Out (LIFO): elements pushed last are popped first.',
  },
  {
    id: 'dsa_beg_3',
    category: 'data_structures',
    difficulty: 'Beginner',
    topic: 'Data Structures',
    concept: 'Binary Tree Nodes',
    type: 'multiple_choice',
    question: 'What is the maximum number of children any node can have in a Binary Tree?',
    options: ['1', '2', '3', 'Unlimited'],
    correctAnswer: '2',
    explanation: 'By definition, every node in a binary tree has at most two children: a left child and a right child.',
  },
  {
    id: 'dsa_beg_4',
    category: 'data_structures',
    difficulty: 'Beginner',
    topic: 'Data Structures',
    concept: 'Queue Structure',
    type: 'true_false',
    question: 'A Queue data structure inserts elements at the rear (enqueue) and removes elements from the front (dequeue).',
    options: ['True', 'False'],
    correctAnswer: 'True',
    explanation: 'True. Queues follow the First-In, First-Out (FIFO) paradigm, enqueuing at the tail and dequeuing from the head.',
  },
  {
    id: 'dsa_beg_5',
    category: 'data_structures',
    difficulty: 'Beginner',
    topic: 'Data Structures',
    concept: 'Hash Map Lookup',
    type: 'short_answer',
    question: 'What is the average-case time complexity of looking up a key in a well-balanced Hash Table? (Format: O(1) or O(N))',
    correctAnswer: 'O(1)',
    explanation: 'Assuming a uniform hash distribution with few collisions, hash table lookup runs in O(1) constant time.',
  },

  // ==========================================
  // 2. DATA STRUCTURES: INTERMEDIATE
  // ==========================================
  {
    id: 'dsa_int_1',
    category: 'data_structures',
    difficulty: 'Intermediate',
    topic: 'Data Structures',
    concept: 'Dynamic Array Geometric Resizing',
    type: 'multiple_choice',
    question: 'Why do dynamic arrays (e.g. Python list, Java ArrayList) double their capacity geometrically rather than incrementing by +1 upon resizing?',
    options: [
      'To prevent heap fragmentation in CPU L1 cache',
      'To ensure that appending N elements takes O(N) total time, achieving amortized O(1) cost per append',
      'To guarantee that memory is zero-initialized automatically',
      'Because operating systems only allocate powers of 2',
    ],
    correctAnswer: 'To ensure that appending N elements takes O(N) total time, achieving amortized O(1) cost per append',
    explanation: 'Doubling capacity requires copying elements exponentially less frequently, reducing the average amortized cost of each append to O(1).',
  },
  {
    id: 'dsa_int_2',
    category: 'data_structures',
    difficulty: 'Intermediate',
    topic: 'Data Structures',
    concept: 'Binary Search Tree Traversal Order',
    type: 'multiple_choice',
    question: 'Which depth-first tree traversal visits nodes of a Binary Search Tree (BST) in strictly ascending sorted order?',
    options: ['Pre-order (Root, Left, Right)', 'In-order (Left, Root, Right)', 'Post-order (Left, Right, Root)', 'Level-order (BFS)'],
    correctAnswer: 'In-order (Left, Root, Right)',
    explanation: 'In-order traversal visits all smaller elements in the left subtree, then the root, then larger elements in the right subtree, producing sorted output.',
  },
  {
    id: 'dsa_int_3',
    category: 'data_structures',
    difficulty: 'Intermediate',
    topic: 'Data Structures',
    concept: 'Binary Heap Invariant',
    type: 'multiple_choice',
    question: 'In a 0-indexed array representation of a complete binary Max-Heap, where is the parent node of index `i` located?',
    options: ['(i - 1) // 2', '2 * i + 1', '2 * i + 2', 'i // 2'],
    correctAnswer: '(i - 1) // 2',
    explanation: 'In zero-indexed binary heap array representations, the parent of index `i` is `floor((i - 1) / 2)`, and children are `2i + 1` and `2i + 2`.',
  },
  {
    id: 'dsa_int_4',
    category: 'data_structures',
    difficulty: 'Intermediate',
    topic: 'Data Structures',
    concept: 'Hash Collision Resolution',
    type: 'true_false',
    question: 'Separate chaining resolves hash collisions by storing multiple colliding key-value pairs in a linked list or bucket at the same hash index.',
    options: ['True', 'False'],
    correctAnswer: 'True',
    explanation: 'True. Separate chaining maintains a linked list or auxiliary search tree at each bucket index to store all colliding entries.',
  },
  {
    id: 'dsa_int_5',
    category: 'data_structures',
    difficulty: 'Intermediate',
    topic: 'Data Structures',
    concept: 'Degenerate BST Worst-Case',
    type: 'multiple_choice',
    question: 'What is the worst-case search time complexity in an unbalanced degenerate Binary Search Tree of N nodes?',
    options: ['O(1)', 'O(log N)', 'O(N)', 'O(N log N)'],
    correctAnswer: 'O(N)',
    explanation: 'When insertions occur in sorted order, an un-self-balancing BST degrades into a linear linked list of height N, requiring O(N) comparisons in the worst case.',
  },

  // ==========================================
  // 2. DATA STRUCTURES: ADVANCED
  // ==========================================
  {
    id: 'dsa_adv_1',
    category: 'data_structures',
    difficulty: 'Advanced',
    topic: 'Data Structures',
    concept: 'AVL Tree Self-Balancing Invariant',
    type: 'multiple_choice',
    question: 'What balance factor constraint must an AVL tree maintain for every single node in the tree?',
    options: [
      'Height(Left) must exactly equal Height(Right)',
      '|Height(Left) - Height(Right)| <= 1',
      'The number of left subtree nodes must equal right subtree nodes',
      'Depth of every leaf must be equal to log2(N)',
    ],
    correctAnswer: '|Height(Left) - Height(Right)| <= 1',
    explanation: 'An AVL tree is strictly height-balanced: for every node, the height difference between left and right subtrees (balance factor) cannot exceed 1.',
  },
  {
    id: 'dsa_adv_2',
    category: 'data_structures',
    difficulty: 'Advanced',
    topic: 'Data Structures',
    concept: 'Disjoint Set Union (DSU) Complexity',
    type: 'multiple_choice',
    question: 'When implementing Disjoint Set Union (DSU) with both Path Compression and Union-by-Rank, what is the amortized time complexity per find/union operation?',
    options: ['O(log N)', 'O(1)', 'O(alpha(N)) — Inverse Ackermann function', 'O(sqrt(N))'],
    correctAnswer: 'O(alpha(N)) — Inverse Ackermann function',
    explanation: 'Combining union by rank and path compression achieves nearly constant amortized time O(alpha(N)), where alpha is the extremely slow-growing Inverse Ackermann function.',
  },
  {
    id: 'dsa_adv_3',
    category: 'data_structures',
    difficulty: 'Advanced',
    topic: 'Data Structures',
    concept: 'B+ Tree Database Indexing Invariant',
    type: 'multiple_choice',
    question: 'Why do relational database engines use B+ Trees instead of standard B-Trees for primary table indexing?',
    options: [
      'B+ Trees require zero disk memory allocations',
      'B+ Trees store all actual record pointers in leaf nodes linked as a contiguous linked list, maximizing range scan efficiency and cache block utilization',
      'B+ Trees eliminate all disk read operations using CPU registers',
      'B+ Trees restrict keys to integer data types only',
    ],
    correctAnswer: 'B+ Trees store all actual record pointers in leaf nodes linked as a contiguous linked list, maximizing range scan efficiency and cache block utilization',
    explanation: 'In B+ Trees, internal nodes only store routing keys (maximizing branching factor per page), while leaves contain all data pointers linked sequentially for fast range queries.',
  },
  {
    id: 'dsa_adv_4',
    category: 'data_structures',
    difficulty: 'Advanced',
    topic: 'Data Structures',
    concept: 'Segment Tree Range Query',
    type: 'short_answer',
    question: 'What is the time complexity of querying the range minimum or range sum in a Segment Tree of size N? (Format: O(log N) or O(N))',
    correctAnswer: 'O(log N)',
    explanation: 'A Segment Tree partitions array intervals into a binary hierarchy of height O(log N), allowing any arbitrary range query to be resolved by visiting at most 4 nodes per level (O(log N)).',
  },
  {
    id: 'dsa_adv_5',
    category: 'data_structures',
    difficulty: 'Advanced',
    topic: 'Data Structures',
    concept: 'Red-Black Tree Properties',
    type: 'true_false',
    question: 'In a valid Red-Black Tree, every simple path from a node to any of its descendant NIL leaves contains the exact same number of black nodes.',
    options: ['True', 'False'],
    correctAnswer: 'True',
    explanation: 'True. This "black-height" invariant guarantees that no path is more than twice as long as any other path, ensuring logarithmic height O(log N).',
  },

  // ==========================================
  // 3. ALGORITHMS: BEGINNER
  // ==========================================
  {
    id: 'algo_beg_1',
    category: 'algorithms',
    difficulty: 'Beginner',
    topic: 'Algorithms & Graph Theory',
    concept: 'Binary Search Precondition',
    type: 'multiple_choice',
    question: 'What fundamental precondition must be satisfied before Binary Search can be applied to an array?',
    options: [
      'The array elements must be unique',
      'The array must be sorted in ascending or descending order',
      'The array length must be a power of 2',
      'The array must contain positive numbers only',
    ],
    correctAnswer: 'The array must be sorted in ascending or descending order',
    explanation: 'Binary Search relies on sorted monotonicity to discard half the search space on each comparison step.',
  },
  {
    id: 'algo_beg_2',
    category: 'algorithms',
    difficulty: 'Beginner',
    topic: 'Algorithms & Graph Theory',
    concept: 'Big-O Growth Hierarchy',
    type: 'multiple_choice',
    question: 'Which of the following algorithmic time complexities grows the SLOWEST as N increases to infinity?',
    options: ['O(N)', 'O(log N)', 'O(N^2)', 'O(N log N)'],
    correctAnswer: 'O(log N)',
    explanation: 'Logarithmic growth O(log N) is exponentially slower than linear O(N), making it the most efficient of the options.',
  },
  {
    id: 'algo_beg_3',
    category: 'algorithms',
    difficulty: 'Beginner',
    topic: 'Algorithms & Graph Theory',
    concept: 'Recursion Base Case',
    type: 'true_false',
    question: 'Every recursive function must contain at least one base case to prevent infinite recursion and stack overflow errors.',
    options: ['True', 'False'],
    correctAnswer: 'True',
    explanation: 'True. Without a terminating base case, recursive calls consume stack frames continuously until maximum recursion depth is exceeded.',
  },
  {
    id: 'algo_beg_4',
    category: 'algorithms',
    difficulty: 'Beginner',
    topic: 'Algorithms & Graph Theory',
    concept: 'Linear Search Complexity',
    type: 'short_answer',
    question: 'What is the worst-case time complexity of Linear Search in an unsorted array of N elements? (Format: O(N) or O(1))',
    correctAnswer: 'O(N)',
    explanation: 'In the worst case, the target element is at the very end of the array or not present at all, requiring checking all N elements.',
  },

  // ==========================================
  // 3. ALGORITHMS: INTERMEDIATE
  // ==========================================
  {
    id: 'algo_int_1',
    category: 'algorithms',
    difficulty: 'Intermediate',
    topic: 'Algorithms & Graph Theory',
    concept: 'BFS vs DFS for Shortest Path',
    type: 'multiple_choice',
    question: 'Why is Breadth-First Search (BFS) used instead of Depth-First Search (DFS) to find the shortest path in an unweighted graph?',
    options: [
      'BFS runs in O(1) memory space',
      'BFS explores nodes level-by-level in order of their edge distance from the source, guaranteeing the first time a target is visited is via the shortest path',
      'DFS cannot detect cycles in undirected graphs',
      'BFS sorts edge weights in descending order',
    ],
    correctAnswer: 'BFS explores nodes level-by-level in order of their edge distance from the source, guaranteeing the first time a target is visited is via the shortest path',
    explanation: 'Because BFS processes vertices in concentric rings by distance, the first arrival at the target node is mathematically guaranteed to be the minimum edge count.',
  },
  {
    id: 'algo_int_2',
    category: 'algorithms',
    difficulty: 'Intermediate',
    topic: 'Algorithms & Graph Theory',
    concept: 'Merge Sort vs Quick Sort Stability',
    type: 'multiple_choice',
    question: 'Which sorting algorithm provides guaranteed O(N log N) worst-case time complexity AND is stable by default?',
    options: ['Quick Sort', 'Merge Sort', 'Heap Sort', 'Selection Sort'],
    correctAnswer: 'Merge Sort',
    explanation: 'Merge Sort divides arrays into sub-arrays and merges them stably with strict O(N log N) worst-case time complexity, whereas Quick Sort can degrade to O(N^2).',
  },
  {
    id: 'algo_int_3',
    category: 'algorithms',
    difficulty: 'Intermediate',
    topic: 'Algorithms & Graph Theory',
    concept: 'Topological Sort Precondition',
    type: 'multiple_choice',
    question: 'Topological sorting is ONLY possible on graphs that are:',
    options: [
      'Complete and weighted',
      'Directed Acyclic Graphs (DAGs)',
      'Undirected bipartite graphs',
      'Strongly connected cyclic graphs',
    ],
    correctAnswer: 'Directed Acyclic Graphs (DAGs)',
    explanation: 'Topological sort requires directed dependency edges with zero cycles (DAG); any cycle creates a circular dependency where no valid linear ordering exists.',
  },
  {
    id: 'algo_int_4',
    category: 'algorithms',
    difficulty: 'Intermediate',
    topic: 'Algorithms & Graph Theory',
    concept: 'Dynamic Programming Principle',
    type: 'true_false',
    question: 'Dynamic programming is applicable to problems that exhibit overlapping subproblems and optimal substructure properties.',
    options: ['True', 'False'],
    correctAnswer: 'True',
    explanation: 'True. Optimal substructure ensures the global optimal solution can be built from optimal solutions to subproblems, and overlapping subproblems allow memoization of redundant work.',
  },
  {
    id: 'algo_int_5',
    category: 'algorithms',
    difficulty: 'Intermediate',
    topic: 'Algorithms & Graph Theory',
    concept: 'Sliding Window Invariant',
    type: 'multiple_choice',
    question: 'When finding the maximum sum subarray of fixed size K in an array of size N, what is the time complexity using the Sliding Window technique?',
    options: ['O(N * K)', 'O(N)', 'O(N^2)', 'O(log N)'],
    correctAnswer: 'O(N)',
    explanation: 'Instead of re-summing K elements for each index (costing O(N*K)), the sliding window subtracts the exiting left element and adds the entering right element in O(1) per step, taking O(N) total.',
  },

  // ==========================================
  // 3. ALGORITHMS: ADVANCED
  // ==========================================
  {
    id: 'algo_adv_1',
    category: 'algorithms',
    difficulty: 'Advanced',
    topic: 'Algorithms & Graph Theory',
    concept: 'Dijkstra with Priority Queue Complexity',
    type: 'multiple_choice',
    question: 'What is the exact time complexity of Dijkstra algorithm on a graph with V vertices and E edges implemented using a Min-Indexed Binary Heap?',
    options: ['O(V^2)', 'O((V + E) * log V)', 'O(V * E)', 'O(E * log E)'],
    correctAnswer: 'O((V + E) * log V)',
    explanation: 'Extracting the minimum vertex happens V times (O(V log V)) and relaxing edges updates heap keys at most E times (O(E log V)), summing to O((V + E) log V).',
  },
  {
    id: 'algo_adv_2',
    category: 'algorithms',
    difficulty: 'Advanced',
    topic: 'Algorithms & Graph Theory',
    concept: 'Bellman-Ford vs Negative Cycles',
    type: 'multiple_choice',
    question: 'How does the Bellman-Ford algorithm detect the presence of negative weight cycles reachable from the source?',
    options: [
      'By checking if any node has an odd degree',
      'By attempting an additional relaxation step on the V-th iteration; if any distance still decreases, a negative cycle exists',
      'By verifying whether DFS detects a forward edge',
      'By counting the number of priority queue re-insertions',
    ],
    correctAnswer: 'By attempting an additional relaxation step on the V-th iteration; if any distance still decreases, a negative cycle exists',
    explanation: 'In a graph with V vertices without negative cycles, shortest paths have at most V-1 edges. If edge relaxation succeeds on step V, distances are being infinitely decreased by a negative cycle.',
  },
  {
    id: 'algo_adv_3',
    category: 'algorithms',
    difficulty: 'Advanced',
    topic: 'Algorithms & Graph Theory',
    concept: '0/1 Knapsack Space Optimization',
    type: 'multiple_choice',
    question: 'When optimizing the 0/1 Knapsack dynamic programming table from a 2D matrix DP[i][w] to a 1D array DP[w], in which direction must the weight loop iterate?',
    options: [
      'From 0 upwards to Capacity W',
      'From Capacity W downwards to item weight w_i',
      'In random order with two pointers',
      'From median capacity outward',
    ],
    correctAnswer: 'From Capacity W downwards to item weight w_i',
    explanation: 'Iterating backward (W down to w_i) ensures that `DP[w - w_i]` refers to the previous item stage rather than including the current item multiple times.',
  },
  {
    id: 'algo_adv_4',
    category: 'algorithms',
    difficulty: 'Advanced',
    topic: 'Algorithms & Graph Theory',
    concept: 'A* Search Admissible Heuristic',
    type: 'true_false',
    question: 'An A* Search heuristic h(n) is admissible if and only if it never overestimates the true minimal cost to reach the target from node n.',
    options: ['True', 'False'],
    correctAnswer: 'True',
    explanation: 'True. Admissibility (h(n) <= h*(n)) is mathematically required for A* to guarantee finding the optimal shortest path.',
  },

  // ==========================================
  // 4. SQL & DATABASES: BEGINNER
  // ==========================================
  {
    id: 'sql_beg_1',
    category: 'sql',
    difficulty: 'Beginner',
    topic: 'SQL & Database Design',
    concept: 'SQL Clause Order of Execution',
    type: 'multiple_choice',
    question: 'In standard SQL execution, which clause is logically evaluated FIRST?',
    options: ['SELECT', 'FROM', 'WHERE', 'ORDER BY'],
    correctAnswer: 'FROM',
    explanation: 'The query processor evaluates `FROM` (and JOINs) first to identify the source tables before applying `WHERE` filters, `GROUP BY`, `SELECT`, and `ORDER BY`.',
  },
  {
    id: 'sql_beg_2',
    category: 'sql',
    difficulty: 'Beginner',
    topic: 'SQL & Database Design',
    concept: 'Primary Key Invariant',
    type: 'multiple_choice',
    question: 'What constraints are intrinsically enforced on a table column designated as a Primary Key?',
    options: [
      'UNIQUE and NOT NULL',
      'FOREIGN KEY and AUTO INCREMENT',
      'INDEXED and READ ONLY',
      'CASCADE DELETE only',
    ],
    correctAnswer: 'UNIQUE and NOT NULL',
    explanation: 'A Primary Key uniquely identifies each row in a relation, requiring both distinct (UNIQUE) and non-missing (NOT NULL) values.',
  },
  {
    id: 'sql_beg_3',
    category: 'sql',
    difficulty: 'Beginner',
    topic: 'SQL & Database Design',
    concept: 'LEFT JOIN Semantics',
    type: 'multiple_choice',
    question: 'What is the output behavior of a `LEFT OUTER JOIN` between Table A (left) and Table B (right)?',
    options: [
      'Returns only rows with matching keys in both tables',
      'Returns all rows from Table A, populating NULL for columns of Table B when no join match exists',
      'Returns all rows from Table B only',
      'Deletes non-matching rows from Table A',
    ],
    correctAnswer: 'Returns all rows from Table A, populating NULL for columns of Table B when no join match exists',
    explanation: 'LEFT JOIN preserves every record from the left table regardless of whether corresponding matches exist in the right table.',
  },
  {
    id: 'sql_beg_4',
    category: 'sql',
    difficulty: 'Beginner',
    topic: 'SQL & Database Design',
    concept: 'NULL Comparisons',
    type: 'true_false',
    question: 'In SQL, evaluating `WHERE column = NULL` evaluates to True when column contains a null value.',
    options: ['True', 'False'],
    correctAnswer: 'False',
    explanation: 'False. In SQL three-valued logic, comparison with NULL using `= NULL` yields UNKNOWN/NULL. One must use `IS NULL` or `IS NOT NULL`.',
  },

  // ==========================================
  // 4. SQL & DATABASES: INTERMEDIATE
  // ==========================================
  {
    id: 'sql_int_1',
    category: 'sql',
    difficulty: 'Intermediate',
    topic: 'SQL & Database Design',
    concept: 'HAVING vs WHERE Clause',
    type: 'multiple_choice',
    question: 'What is the key functional distinction between the `WHERE` and `HAVING` clauses in SQL?',
    options: [
      '`WHERE` filters grouped aggregated rows, whereas `HAVING` filters individual rows before grouping',
      '`WHERE` filters individual rows prior to aggregation; `HAVING` filters group results after `GROUP BY` aggregations',
      '`HAVING` only works with integer primary keys',
      '`WHERE` cannot be used in queries with JOINs',
    ],
    correctAnswer: '`WHERE` filters individual rows prior to aggregation; `HAVING` filters group results after `GROUP BY` aggregations',
    explanation: '`WHERE` evaluates on raw table rows before grouping occurs. `HAVING` filters post-aggregation groups (e.g. `HAVING COUNT(*) > 5`).',
  },
  {
    id: 'sql_int_2',
    category: 'sql',
    difficulty: 'Intermediate',
    topic: 'SQL & Database Design',
    concept: 'Third Normal Form (3NF)',
    type: 'multiple_choice',
    question: 'A relational database table is in Third Normal Form (3NF) if it is in 2NF and contains no:',
    options: [
      'Foreign key constraints',
      'Transitive functional dependencies (non-key attribute determining another non-key attribute)',
      'Primary key indices',
      'Composite keys',
    ],
    correctAnswer: 'Transitive functional dependencies (non-key attribute determining another non-key attribute)',
    explanation: '3NF requires that every non-prime attribute is non-transitively dependent on every candidate key (X -> Y and Y -> Z where Z is non-prime is disallowed).',
  },
  {
    id: 'sql_int_3',
    category: 'sql',
    difficulty: 'Intermediate',
    topic: 'SQL & Database Design',
    concept: 'B-Tree Composite Index Leftmost Prefix Rule',
    type: 'multiple_choice',
    question: 'Given an index `CREATE INDEX idx_user ON users(last_name, first_name, age)`, which query CANNOT effectively utilize the B-Tree index?',
    options: [
      '`WHERE last_name = "Smith" AND first_name = "John"`',
      '`WHERE last_name = "Smith"`',
      '`WHERE first_name = "John" AND age = 25`',
      '`WHERE last_name = "Smith" AND age = 25`',
    ],
    correctAnswer: '`WHERE first_name = "John" AND age = 25`',
    explanation: 'B-Tree composite indexes follow the Leftmost Prefix Rule. Queries omitting the leading column (`last_name`) cannot perform an index range scan.',
  },
  {
    id: 'sql_int_4',
    category: 'sql',
    difficulty: 'Intermediate',
    topic: 'SQL & Database Design',
    concept: 'SQL Window Functions',
    type: 'multiple_choice',
    question: 'What does `DENSE_RANK() OVER (PARTITION BY department_id ORDER BY salary DESC)` produce when two employees share the identical highest salary?',
    options: [
      'Both receive rank 1, and the next employee receives rank 3',
      'Both receive rank 1, and the next employee receives rank 2 without skipping rank numbers',
      'Raises a runtime duplicate key error',
      'Assigns rank 1 to the first employee and rank 2 to the second randomly',
    ],
    correctAnswer: 'Both receive rank 1, and the next employee receives rank 2 without skipping rank numbers',
    explanation: 'Unlike standard `RANK()` (which skips numbers on ties e.g. 1, 1, 3), `DENSE_RANK()` leaves no gaps in ranking sequences (e.g. 1, 1, 2).',
  },

  // ==========================================
  // 4. SQL & DATABASES: ADVANCED
  // ==========================================
  {
    id: 'sql_adv_1',
    category: 'sql',
    difficulty: 'Advanced',
    topic: 'SQL & Database Design',
    concept: 'Transaction Isolation & Phantom Reads',
    type: 'multiple_choice',
    question: 'Which transaction isolation level is the MINIMUM level required to prevent Phantom Reads in standard SQL?',
    options: ['Read Uncommitted', 'Read Committed', 'Repeatable Read / Serializable', 'Snapshot Isolation only'],
    correctAnswer: 'Repeatable Read / Serializable',
    explanation: 'Phantom reads occur when a transaction re-executes a range query and discovers newly inserted rows committed by a concurrent transaction. Serializable (and PostgreSQL Repeatable Read) prevents this.',
  },
  {
    id: 'sql_adv_2',
    category: 'sql',
    difficulty: 'Advanced',
    topic: 'SQL & Database Design',
    concept: 'PostgreSQL MVCC Snapshot Isolation',
    type: 'multiple_choice',
    question: 'How does Multi-Version Concurrency Control (MVCC) allow readers and writers to avoid blocking each other in PostgreSQL?',
    options: [
      'By acquiring exclusive table-level locks during every write',
      'By storing row version tuples with `xmin` and `xmax` transaction IDs, so readers inspect a point-in-time snapshot while writers create new row versions',
      'By caching all transactions in memory and flushing sequentially',
      'By executing queries exclusively on read-only replicas',
    ],
    correctAnswer: 'By storing row version tuples with `xmin` and `xmax` transaction IDs, so readers inspect a point-in-time snapshot while writers create new row versions',
    explanation: 'MVCC decouples readers from writers: `UPDATE` statements create a new version of the row marked with the current transaction ID without locking concurrent readers.',
  },
  {
    id: 'sql_adv_3',
    category: 'sql',
    difficulty: 'Advanced',
    topic: 'SQL & Database Design',
    concept: 'Write-Ahead Logging (WAL) & Durability',
    type: 'true_false',
    question: 'Write-Ahead Logging (WAL) ensures database Durability by writing and flushing transaction modification records to sequential disk storage before dirty buffer pool pages are written to data files.',
    options: ['True', 'False'],
    correctAnswer: 'True',
    explanation: 'True. If the server crashes, the database engine replays the WAL during recovery (Redo/Undo) to restore all committed transactions to a consistent state.',
  },
  {
    id: 'sql_adv_4',
    category: 'sql',
    difficulty: 'Advanced',
    topic: 'SQL & Database Design',
    concept: 'Hash Join vs Nested Loop Join Algorithm',
    type: 'multiple_choice',
    question: 'When the query optimizer chooses a Hash Join over a Nested Loop Join for an equi-join `A.id = B.id`, what is the algorithmic strategy?',
    options: [
      'It iterates over table A with an inner loop over table B in O(N*M)',
      'It builds an in-memory hash table on the smaller relation, then scans the larger relation probing keys in O(N + M) total time',
      'It sorts both tables on disk using external merge sort',
      'It generates all possible Cartesian cross product permutations',
    ],
    correctAnswer: 'It builds an in-memory hash table on the smaller relation, then scans the larger relation probing keys in O(N + M) total time',
    explanation: 'Hash Join constructs a hash table on the build input (smaller table) in O(N) and streams the probe input (larger table) in O(M), achieving linear execution time.',
  },

  // ==========================================
  // 5. MACHINE LEARNING: BEGINNER
  // ==========================================
  {
    id: 'ml_beg_1',
    category: 'machine_learning',
    difficulty: 'Beginner',
    topic: 'Machine Learning & AI',
    concept: 'Supervised Learning Definition',
    type: 'multiple_choice',
    question: 'What characterizes Supervised Machine Learning compared to Unsupervised Learning?',
    options: [
      'The model clusters unlabelled data points without guidance',
      'The training dataset includes input features paired with target ground-truth labels',
      'The model interacts with an environment receiving reward signals',
      'The model operates strictly on tabular CSV files',
    ],
    correctAnswer: 'The training dataset includes input features paired with target ground-truth labels',
    explanation: 'Supervised learning trains mathematical algorithms to map input features to known target outputs using ground-truth labeled examples.',
  },
  {
    id: 'ml_beg_2',
    category: 'machine_learning',
    difficulty: 'Beginner',
    topic: 'Machine Learning & AI',
    concept: 'Overfitting vs Generalization',
    type: 'multiple_choice',
    question: 'What is a hallmark symptom of a model suffering from severe Overfitting?',
    options: [
      'High training loss and high validation loss',
      'Near-zero training loss but significantly high error on unseen test/validation data',
      'Extremely fast inference speed',
      'Low parameter count',
    ],
    correctAnswer: 'Near-zero training loss but significantly high error on unseen test/validation data',
    explanation: 'Overfitting occurs when a model memorizes training noise rather than general patterns, resulting in excellent training accuracy but poor validation performance.',
  },
  {
    id: 'ml_beg_3',
    category: 'machine_learning',
    difficulty: 'Beginner',
    topic: 'Machine Learning & AI',
    concept: 'Bias-Variance Tradeoff',
    type: 'true_false',
    question: 'High bias typically leads to underfitting because the model is too simplistic to capture underlying data relationships.',
    options: ['True', 'False'],
    correctAnswer: 'True',
    explanation: 'True. High bias reflects strong erroneous model assumptions (underfitting), while high variance reflects sensitivity to small fluctuations in training data (overfitting).',
  },

  // ==========================================
  // 5. MACHINE LEARNING: INTERMEDIATE
  // ==========================================
  {
    id: 'ml_int_1',
    category: 'machine_learning',
    difficulty: 'Intermediate',
    topic: 'Machine Learning & AI',
    concept: 'L1 (Lasso) vs L2 (Ridge) Regularization',
    type: 'multiple_choice',
    question: 'What distinct mathematical property differentiates L1 (Lasso) regularization from L2 (Ridge) regularization?',
    options: [
      'L1 adds quadratic weight penalties; L2 adds absolute weight penalties',
      'L1 penalizes absolute weights, driving non-informative feature weights strictly to zero (inducing sparsity)',
      'L2 guarantees zero training error',
      'L1 cannot be used with neural networks',
    ],
    correctAnswer: 'L1 penalizes absolute weights, driving non-informative feature weights strictly to zero (inducing sparsity)',
    explanation: 'L1 regularization utilizes the absolute value norm (|w|), whose sharp geometric diamond corners frequently intersect axes, driving irrelevant weights to zero.',
  },
  {
    id: 'ml_int_2',
    category: 'machine_learning',
    difficulty: 'Intermediate',
    topic: 'Machine Learning & AI',
    concept: 'ROC-AUC & Classification Metrics',
    type: 'multiple_choice',
    question: 'On an imbalanced dataset where 99% of samples belong to the negative class, why is Accuracy a misleading performance metric?',
    options: [
      'Because accuracy cannot compute float values',
      'A trivial classifier predicting the negative class 100% of the time scores 99% accuracy while detecting 0 true positives',
      'Accuracy is undefined for binary classification',
      'ROC-AUC requires balanced sample distributions',
    ],
    correctAnswer: 'A trivial classifier predicting the negative class 100% of the time scores 99% accuracy while detecting 0 true positives',
    explanation: 'Class imbalance makes accuracy deceptive. Precision, Recall, PR-AUC, and F1-Score must be used to evaluate true positive detection capability.',
  },
  {
    id: 'ml_int_3',
    category: 'machine_learning',
    difficulty: 'Intermediate',
    topic: 'Machine Learning & AI',
    concept: 'Backpropagation & Autograd',
    type: 'true_false',
    question: 'Backpropagation computes the partial derivatives of the loss function with respect to every trainable weight using the calculus Chain Rule.',
    options: ['True', 'False'],
    correctAnswer: 'True',
    explanation: 'True. Backpropagation applies the multivariable chain rule from output loss backward through computational graph layers to calculate gradients.',
  },

  // ==========================================
  // 5. MACHINE LEARNING: ADVANCED
  // ==========================================
  {
    id: 'ml_adv_1',
    category: 'machine_learning',
    difficulty: 'Advanced',
    topic: 'Machine Learning & AI',
    concept: 'Transformer Self-Attention Formulation',
    type: 'multiple_choice',
    question: 'In the Transformer scaled dot-product attention formula `Softmax((Q * K^T) / sqrt(d_k)) * V`, what is the purpose of dividing by `sqrt(d_k)`?',
    options: [
      'To prevent matrix multiplication overflow in GPU FP16 registers',
      'To prevent dot products from growing excessively large for high dimensions, which would push the Softmax into regions with vanishingly small gradients',
      'To convert attention weights into integer logits',
      'To normalize positional encodings across variable sequence lengths',
    ],
    correctAnswer: 'To prevent dot products from growing excessively large for high dimensions, which would push the Softmax into regions with vanishingly small gradients',
    explanation: 'For large key dimensionality d_k, dot products scale with d_k. Scaling by 1/sqrt(d_k) preserves variance of 1, preventing softmax saturation and vanishing gradients.',
  },
  {
    id: 'ml_adv_2',
    category: 'machine_learning',
    difficulty: 'Advanced',
    topic: 'Machine Learning & AI',
    concept: 'LoRA (Low-Rank Adaptation) Parameter Mechanics',
    type: 'multiple_choice',
    question: 'How does LoRA (Low-Rank Adaptation) achieve memory-efficient parameter fine-tuning of large language models?',
    options: [
      'By deleting 90% of model transformer layers',
      'By freezing original weight matrix W_0 (d x k) and decomposing updates into two low-rank matrices B (d x r) and A (r x k) where rank r << min(d, k)',
      'By converting all float weights into 1-bit boolean masks',
      'By training prompt tokens exclusively without backpropagation',
    ],
    correctAnswer: 'By freezing original weight matrix W_0 (d x k) and decomposing updates into two low-rank matrices B (d x r) and A (r x k) where rank r << min(d, k)',
    explanation: 'LoRA represents weight update delta W as the product B * A with rank r (e.g. r=8 or 16), reducing trainable parameters by up to 99.9% while keeping baseline weights frozen.',
  },
  {
    id: 'ml_adv_3',
    category: 'machine_learning',
    difficulty: 'Advanced',
    topic: 'Machine Learning & AI',
    concept: 'KV-Cache in Autoregressive LLM Inference',
    type: 'true_false',
    question: 'The Key-Value (KV) Cache avoids recalculating attention Keys and Values for preceding prompt tokens during autoregressive token-by-token generation.',
    options: ['True', 'False'],
    correctAnswer: 'True',
    explanation: 'True. Instead of recomputing attention over all prior tokens for each new token generated (costing O(N^2)), caching past K and V tensors reduces per-step attention to O(N).',
  },

  // ==========================================
  // 6. SYSTEM DESIGN: BEGINNER
  // ==========================================
  {
    id: 'sys_beg_1',
    category: 'system_design',
    difficulty: 'Beginner',
    topic: 'System Design & Scalability',
    concept: 'Vertical vs Horizontal Scaling',
    type: 'multiple_choice',
    question: 'What is Horizontal Scaling (Scaling Out) in distributed systems?',
    options: [
      'Upgrading CPU, RAM, and SSD capacity of a single physical server',
      'Adding more server instances and distributing network traffic across the cluster',
      'Converting monolithic backend code into microservices',
      'Compressing network packets using gzip',
    ],
    correctAnswer: 'Adding more server instances and distributing network traffic across the cluster',
    explanation: 'Horizontal scaling adds more machines to pool computing power, whereas vertical scaling upgrades existing machine hardware.',
  },
  {
    id: 'sys_beg_2',
    category: 'system_design',
    difficulty: 'Beginner',
    topic: 'System Design & Scalability',
    concept: 'Load Balancer Role',
    type: 'multiple_choice',
    question: 'What is the primary role of a Load Balancer in modern web infrastructure?',
    options: [
      'Compiling frontend TypeScript code on client devices',
      'Evenly distributing incoming client network requests across multiple healthy backend application servers',
      'Encrypting hard drives on disk storage nodes',
      'Managing database schema migrations',
    ],
    correctAnswer: 'Evenly distributing incoming client network requests across multiple healthy backend application servers',
    explanation: 'Load balancers prevent server overload, maximize throughput, and enable high availability by rerouting around failed nodes.',
  },

  // ==========================================
  // 6. SYSTEM DESIGN: INTERMEDIATE
  // ==========================================
  {
    id: 'sys_int_1',
    category: 'system_design',
    difficulty: 'Intermediate',
    topic: 'System Design & Scalability',
    concept: 'Cache Invalidation Strategies',
    type: 'multiple_choice',
    question: 'In a Cache-Aside (Lazy Loading) caching pattern, what sequence of events occurs on a Cache Miss?',
    options: [
      'The cache writes directly to the disk without notifying the client',
      'Application attempts to read from cache -> Cache Miss -> Application queries database -> Application stores result in cache -> Returns to client',
      'Application immediately raises a 404 error',
      'The database updates the cache in real-time before queries arrive',
    ],
    correctAnswer: 'Application attempts to read from cache -> Cache Miss -> Application queries database -> Application stores result in cache -> Returns to client',
    explanation: 'Cache-aside places the application code in charge of lazily populating the cache upon misses and reading directly from the database.',
  },
  {
    id: 'sys_int_2',
    category: 'system_design',
    difficulty: 'Intermediate',
    topic: 'System Design & Scalability',
    concept: 'CAP Theorem Invariant',
    type: 'multiple_choice',
    question: 'According to the CAP Theorem, in the presence of a network Network Partition (P), a distributed system MUST choose between:',
    options: [
      'Throughput vs Latency',
      'Consistency (CP) vs Availability (AP)',
      'Security vs Storage Cost',
      'SQL vs NoSQL',
    ],
    correctAnswer: 'Consistency (CP) vs Availability (AP)',
    explanation: 'When network partitions occur, a distributed system must either return errors to preserve absolute data consistency (CP) or serve potentially stale data to remain available (AP).',
  },
  {
    id: 'sys_int_3',
    category: 'system_design',
    difficulty: 'Intermediate',
    topic: 'System Design & Scalability',
    concept: 'Rate Limiting Algorithms',
    type: 'multiple_choice',
    question: 'Which rate-limiting algorithm allows brief bursts of traffic up to a bucket capacity while refilling tokens at a constant steady rate?',
    options: ['Fixed Window Counter', 'Token Bucket', 'Sliding Window Log', 'Round Robin'],
    correctAnswer: 'Token Bucket',
    explanation: 'The Token Bucket algorithm accumulates tokens at a fixed rate and allows requests as long as tokens remain, gracefully accommodating bursty traffic.',
  },

  // ==========================================
  // 6. SYSTEM DESIGN: ADVANCED
  // ==========================================
  {
    id: 'sys_adv_1',
    category: 'system_design',
    difficulty: 'Advanced',
    topic: 'System Design & Scalability',
    concept: 'Consistent Hashing & Virtual Nodes',
    type: 'multiple_choice',
    question: 'Why do distributed caches (e.g. Cassandra, Dynamo, Memcached) use Consistent Hashing with Virtual Nodes rather than simple modulo hashing (`hash(key) % N`)?',
    options: [
      'Modulo hashing cannot store string keys',
      'When adding or removing servers, modulo hashing invalidates and remaps almost all keys (O(K)), whereas Consistent Hashing only moves K/N keys and virtual nodes prevent uneven hotspots',
      'Consistent Hashing guarantees zero network latency',
      'Virtual nodes eliminate the need for load balancers',
    ],
    correctAnswer: 'When adding or removing servers, modulo hashing invalidates and remaps almost all keys (O(K)), whereas Consistent Hashing only moves K/N keys and virtual nodes prevent uneven hotspots',
    explanation: 'Consistent Hashing maps servers and keys onto a virtual ring, ensuring adding/removing nodes only impacts adjacent keys rather than triggering a global cache rehash.',
  },
  {
    id: 'sys_adv_2',
    category: 'system_design',
    difficulty: 'Advanced',
    topic: 'System Design & Scalability',
    concept: 'Distributed Saga Pattern vs 2PC',
    type: 'multiple_choice',
    question: 'Why is the Saga Pattern preferred over Two-Phase Commit (2PC) for transactions spanning multiple independent microservices?',
    options: [
      '2PC is a blocking protocol holding database locks across network boundaries, causing latency bottlenecks and availability fragility in distributed systems',
      'Sagas guarantee strict ACID serializable isolation',
      '2PC cannot work with relational databases',
      'Sagas eliminate the need for compensating transactions',
    ],
    correctAnswer: '2PC is a blocking protocol holding database locks across network boundaries, causing latency bottlenecks and availability fragility in distributed systems',
    explanation: '2PC holds row locks until all participants prepare, creating severe latency bottlenecks. Sagas execute local transactions sequentially and use compensating actions if failures occur.',
  },
];
