import { UserProfile, SkillItem, RoadmapNode, AnalyzedDocument, AnalyticsData } from '../types/index.js';

export const DEFAULT_USER_PROFILE: UserProfile = {
  id: 'usr_synapse_01',
  name: 'Alex Rivera',
  email: 'alex.rivera@synapse.edu',
  careerGoal: 'Software Engineer',
  experienceLevel: 'Intermediate',
  weeklyHours: 12,
  learningStyle: 'Interactive Code-First',
  streakDays: 6,
  overallScore: 78,
  completedTopicsCount: 14,
  totalStudyHours: 42.5,
  createdAt: new Date().toISOString(),
};

export const DEFAULT_SKILLS: SkillItem[] = [
  {
    id: 'sk_py',
    name: 'Python Core & OOP',
    category: 'Programming',
    currentLevel: 82,
    targetLevel: 95,
    status: 'Proficient',
    gapReason: 'Solid foundation in syntax and object-oriented design; needs advanced concurrency and metaclasses.',
  },
  {
    id: 'sk_dsa',
    name: 'Data Structures & Algorithms',
    category: 'Computer Science',
    currentLevel: 54,
    targetLevel: 90,
    status: 'In Progress',
    gapReason: 'Comfortable with arrays and hash maps; struggles with recursive backtracking and dynamic programming.',
  },
  {
    id: 'sk_sql',
    name: 'SQL & Database Design',
    category: 'Backend',
    currentLevel: 35,
    targetLevel: 80,
    status: 'Critical Gap',
    gapReason: 'Basic SELECT queries understood, but lacks indexing strategy, transaction isolation, and schema normalization.',
  },
  {
    id: 'sk_sys',
    name: 'System Design & Scalability',
    category: 'Architecture',
    currentLevel: 25,
    targetLevel: 75,
    status: 'Critical Gap',
    gapReason: 'Has not yet implemented distributed caching (Redis), message queues (Kafka), or horizontal load balancing.',
  },
  {
    id: 'sk_web',
    name: 'RESTful API Engineering',
    category: 'Backend',
    currentLevel: 70,
    targetLevel: 85,
    status: 'Proficient',
    gapReason: 'Good API structuring; needs authentication flows (JWT/OAuth2) and rate limiting.',
  },
  {
    id: 'sk_git',
    name: 'Git & CI/CD Workflows',
    category: 'DevOps',
    currentLevel: 65,
    targetLevel: 80,
    status: 'Proficient',
    gapReason: 'Comfortable with branching/PRs; needs GitHub Actions pipeline automation.',
  },
];

export const DEFAULT_ROADMAP_NODES: RoadmapNode[] = [
  {
    id: 'node_1',
    title: 'Python Functions, Scope & Closures',
    stage: 'Foundations',
    description: 'Master first-class functions, args/kwargs unpacking, decorators, and lexical scoping mechanisms.',
    estimatedHours: 3.5,
    status: 'completed',
    orderIndex: 1,
    prerequisites: ['Basic Syntax', 'Control Flow'],
    skillsCovered: ['Python Core & OOP'],
    whyRecommended: 'Essential baseline required for idiomatic Python design patterns and test-driven development.',
    confidenceScore: 98,
    recommendationState: 'active',
  },
  {
    id: 'node_2',
    title: 'Linear Data Structures: Lists & Hash Tables',
    stage: 'Core Engineering',
    description: 'Implement dynamic arrays, collision resolution in hash maps, and analyze amortized O(1) complexities.',
    estimatedHours: 4.0,
    status: 'completed',
    orderIndex: 2,
    prerequisites: ['Python Functions'],
    skillsCovered: ['Data Structures & Algorithms'],
    whyRecommended: 'Forms 60% of foundational coding interview questions and day-to-day backend data handling.',
    confidenceScore: 96,
    recommendationState: 'active',
  },
  {
    id: 'node_3',
    title: 'Non-Linear Structures: Trees & Binary Search',
    stage: 'Core Engineering',
    description: 'Traverse binary trees (DFS/BFS), balance properties, and master iterative vs recursive approaches.',
    estimatedHours: 5.0,
    status: 'in_progress',
    orderIndex: 3,
    prerequisites: ['Linear Data Structures'],
    skillsCovered: ['Data Structures & Algorithms'],
    whyRecommended: 'Identified as a critical pivot point for advancing your problem-solving rating from 54% to 75%.',
    confidenceScore: 94,
    recommendationState: 'active',
  },
  {
    id: 'node_4',
    title: 'Graph Algorithms: BFS, DFS & Shortest Path',
    stage: 'Advanced Algorithms',
    description: 'Model network topologies, cycle detection with topological sort, and implement Dijkstra algorithm.',
    estimatedHours: 6.5,
    status: 'available',
    orderIndex: 4,
    prerequisites: ['Trees & Binary Search'],
    skillsCovered: ['Data Structures & Algorithms'],
    whyRecommended: 'High relevance for technical screening rounds at tier-1 tech firms.',
    confidenceScore: 92,
    recommendationState: 'active',
  },
  {
    id: 'node_5',
    title: 'Relational Schema Design & SQL Optimization',
    stage: 'Core Engineering',
    description: 'Design 3NF relational schemas, execute complex JOINs, and optimize queries with B-Tree indices.',
    estimatedHours: 5.5,
    status: 'available',
    orderIndex: 5,
    prerequisites: ['Python Core & OOP'],
    skillsCovered: ['SQL & Database Design'],
    whyRecommended: 'Directly addresses your 35% database skill deficit identified during initial profile assessment.',
    confidenceScore: 95,
    recommendationState: 'active',
  },
  {
    id: 'node_6',
    title: 'Microservices & Event-Driven Architecture',
    stage: 'Real-World Projects',
    description: 'Build an end-to-end distributed order processing service with asynchronous pub/sub messaging.',
    estimatedHours: 8.0,
    status: 'locked',
    orderIndex: 6,
    prerequisites: ['RESTful API Engineering', 'Relational Schema Design'],
    skillsCovered: ['System Design & Scalability', 'RESTful API Engineering'],
    whyRecommended: 'Portfolio-grade capstone required to bridge the gap to Senior/Mid-level engineering competencies.',
    confidenceScore: 90,
    recommendationState: 'active',
  },
  {
    id: 'node_7',
    title: 'Distributed Caching & High-Throughput APIs',
    stage: 'Specialization',
    description: 'Implement Redis cache-aside strategies, cache invalidation, and rate limiting algorithms.',
    estimatedHours: 6.0,
    status: 'locked',
    orderIndex: 7,
    prerequisites: ['Microservices Architecture'],
    skillsCovered: ['System Design & Scalability'],
    whyRecommended: 'Crucial for passing systems engineering interviews.',
    confidenceScore: 89,
    recommendationState: 'active',
  },
  {
    id: 'node_8',
    title: 'Live Technical Mock Interview Simulation',
    stage: 'Interview & Job Ready',
    description: 'Timed live algorithmic and architectural simulation with AI critique on complexity and clarity.',
    estimatedHours: 4.0,
    status: 'locked',
    orderIndex: 8,
    prerequisites: ['Graph Algorithms', 'Distributed Caching'],
    skillsCovered: ['Data Structures & Algorithms', 'System Design & Scalability'],
    whyRecommended: 'Final readiness milestone prior to live industry application submissions.',
    confidenceScore: 97,
    recommendationState: 'active',
  },
];

export const DEFAULT_DOCUMENTS: AnalyzedDocument[] = [
  {
    id: 'doc_dsa_notes',
    filename: 'MIT_6.006_Algorithms_LectureNotes.pdf',
    uploadedAt: new Date(Date.now() - 86400000 * 2).toISOString(),
    fileSize: 2450000,
    textSnippet: 'Introduction to Algorithms, Asymptotic Notation, Divide and Conquer, Dynamic Programming, Graph Traversal...',
    conceptsExtracted: ['Asymptotic Analysis (Big O)', 'Divide and Conquer', 'Memoization & Tabulation', 'Topological Sort', 'Dijkstra'],
    prerequisiteGaps: ['Dynamic Programming Formulation', 'Disjoint Set Union'],
    masteredConceptsFound: ['Big O Notation', 'Binary Search'],
    relevanceScore: 94,
    recommendedNodesToInject: ['Dynamic Programming Deep Dive'],
  },
];

export const DEFAULT_ANALYTICS: AnalyticsData = {
  weeklyActivity: [
    { day: 'Mon', hours: 2.5, target: 2.0 },
    { day: 'Tue', hours: 1.8, target: 2.0 },
    { day: 'Wed', hours: 3.2, target: 2.0 },
    { day: 'Thu', hours: 2.0, target: 2.0 },
    { day: 'Fri', hours: 0.8, target: 2.0 },
    { day: 'Sat', hours: 3.5, target: 2.0 },
    { day: 'Sun', hours: 2.2, target: 2.0 },
  ],
  skillRadar: [
    { skill: 'Python Core', current: 82, target: 95, fullMark: 100 },
    { skill: 'Data Structures', current: 54, target: 90, fullMark: 100 },
    { skill: 'SQL & DBs', current: 35, target: 80, fullMark: 100 },
    { skill: 'System Design', current: 25, target: 75, fullMark: 100 },
    { skill: 'REST APIs', current: 70, target: 85, fullMark: 100 },
    { skill: 'Git & CI/CD', current: 65, target: 80, fullMark: 100 },
  ],
  quizPerformance: [
    { date: 'Aug 24', topic: 'Python OOP', score: 88 },
    { date: 'Aug 26', topic: 'Linear DSA', score: 76 },
    { date: 'Aug 29', topic: 'Binary Trees', score: 62 },
    { date: 'Aug 31', topic: 'SQL Queries', score: 45 },
  ],
  aiInsights: [
    {
      id: 'ins_1',
      type: 'positive',
      title: 'Accelerated Python Velocity',
      message: 'You completed Python OOP modules 35% faster than average cohort benchmarks with 88% quiz retention.',
    },
    {
      id: 'ins_2',
      type: 'warning',
      title: 'Recursion & Tree Traversal Friction',
      message: 'Quiz telemetry indicates recurring confusion in recursive termination conditions. Recommended 30m refresher.',
      actionLabel: 'Review Recursion Node',
      actionTarget: 'node_3',
    },
    {
      id: 'ins_3',
      type: 'recommendation',
      title: 'Bridge the SQL Normalization Gap',
      message: 'Your career target as Software Engineer requires database mastery. SQL module is prioritized for this week.',
      actionLabel: 'Start SQL Module',
      actionTarget: 'node_5',
    },
  ],
};
